(define memories
  '((memory flash (address (#xa000 . #xbfff))
            (section (programStart #xa000)
                     reset code idata cdata switch data_init_table)
            (fill 0))
    (memory RAM (address (#x9a00 . #x9fff))
            (section cstack data zdata heap))
    (memory ZPAGE (address (#x00 . #xff))
            (section (registers (#xca . #xff))))
    (memory STACK (address (#x100 . #x1ff))
            (section (stack (#x100 . #x1ff))))
    (block cstack (size #x100))
    (block stack (size #x100))
    (block heap (size #x00))
    ))
